function GUI_neural_ga
%% ********************Graphical User Interface****************************
%% *********Patern Recognition using neural-genetic algorithm************** 

close all;
clear all;
clc;

%Colors for controls 
panel_color=[0.55 0.75 0.65];
entryField_color=[1 1 1];
p_color=[0.5 0.5 0.5];
But_color=[0.2 0.8 0.5];
Result_color=[0.8 0.5 0.9];

%********************Handles & Controls Define****************************

%main figure contain main panel
hFigure=figure(...
    'Units','Pixels',...
    'Position',[100 100 550 400],...
    'Toolbar','none',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Color',[.5 .5 .5],...
    'Name','Image Classification Neural-Genetic');

%main panel contain all controls
hPanel=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[0 0 550 400],...
    'BackgroundColor',panel_color);

hGAl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 370 210 20],...
    'String','Genetic Algorithm Parameters',...
    'BackgroundColor',p_color);

hPopsz=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 340 100 25],...
    'String','12',...
    'BackgroundColor',entryField_color);

hPopszl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 340 100 17],...
    'String','Population Size',...
    'BackgroundColor',panel_color);

hMuRt=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 310 100 25],...
    'String','0.2',...
    'BackgroundColor',entryField_color);

hMuRtl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 310 100 17],...
    'String','Mutation Rate',...
    'BackgroundColor',panel_color);

hCoRt=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 280 100 25],...
    'String','0.5',...
    'BackgroundColor',entryField_color);

hCoRtl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 280 100 17],...
    'String','Crossover Rate',...
    'BackgroundColor',panel_color);

hGen=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 250 100 25],...
    'String','20',...
    'BackgroundColor',entryField_color);

hGenl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 250 110 17],...
    'String','Number of Generation',...
    'BackgroundColor',panel_color);

hLoCl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 230 200 17],...
    'String','Length of Chromosomes = 6600',...
    'BackgroundColor',entryField_color);
hGARsl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 200 100 20],...
    'String','Genetic Result',...
    'BackgroundColor',p_color);

hGToF=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 170 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hGToFl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 170 100 17],...
    'String','Total Fitness',...
    'BackgroundColor',panel_color);
%*******************************************
hNePrl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 370 210 20],...
    'String','Neural Network Parameters',...
    'BackgroundColor',p_color);

hNuIm=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 340 100 25],...
    'String','12',...
    'BackgroundColor',entryField_color);

hNuIml=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[355 340 100 17],...
    'String','Number of Images',...
    'BackgroundColor',panel_color);

hLR=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 310 100 25],...
    'String','0.4',...
    'BackgroundColor',entryField_color);

hLRl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[355 310 100 17],...
    'String','Learning Rate',...
    'BackgroundColor',panel_color);
hMom=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 280 100 25],...
    'String','0.06',...
    'BackgroundColor',entryField_color);

hMoml=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[355 280 100 17],...
    'String','Momentum',...
    'BackgroundColor',panel_color);
hepoch=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 250 100 25],...
    'String','125',...
    'BackgroundColor',entryField_color);

hepochl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[355 250 100 17],...
    'String','Epoch Number',...
    'BackgroundColor',panel_color);
hhiden=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 230 200 17],...
    'String','Hidden Nodes = 60',...
    'BackgroundColor',entryField_color);
hinp=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 210 200 17],...
    'String','Input Nodes = 100',...
    'BackgroundColor',entryField_color);
hout=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 190 200 17],...
    'String','Output Nodes = 10',...
    'BackgroundColor',entryField_color);
hlink=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 190 200 17],...
    'String','Number of Links = 6600',...
    'BackgroundColor',entryField_color);
hGARsl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[300 160 120 20],...
    'String','Neural Netwrk Results',...
    'BackgroundColor',p_color);
hFR=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[300 130 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hFRl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[405 130 90 17],...
    'String','Failure Rate',...
    'BackgroundColor',panel_color);
hTSSE=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[300 100 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hTSSEl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[405 100 90 17],...
    'String','TSSE',...
    'BackgroundColor',panel_color);

hR=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 120 100 25],...
    'FontSize',14,...
    'String','0.7',...
    'BackgroundColor',entryField_color);

hRl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[105 120 170 17],...
    'FontSize',9,...
    'String','Random Weights Boundary',...
    'BackgroundColor',panel_color);

hPanel1=uipanel(...
    'Parent', hPanel,...
    'Units','Pixels',...
    'Position',[0 0 270 110],...
    'BackgroundColor',[.2 .4 .7]);
hNeGaRsl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[5 85 250 17],...
    'String','Neural Genetic System Results',...
    'BackgroundColor',p_color);
hFR1=uicontrol(...
    'Style','Text',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[10 55 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hFR1l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[115 55 90 17],...
    'String','Failure Rate',...
    'BackgroundColor',panel_color);
hTSSE1=uicontrol(...
    'Style','Text',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[10 15 100 25],...
    'FontSize',14,...
    'BackgroundColor',Result_color);

hTSSE1l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[115 15 90 17],...
    'String','TSSE',...
    'BackgroundColor',panel_color);

hRTimel=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[440 40 100 20],...
    'String','Running Time',...
    'BackgroundColor',p_color);
hRTime=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[440 15 100 20],...
    'FontSize',14,...
    'BackgroundColor',Result_color);
hButton=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[285 10 150 25],...
    'String','Genetic Algorithm Start',...
    'BackgroundColor',But_color,...
    'Callback',@Start_GA_callback);

hButton1=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[285 40 150 25],...
    'String','Neural Network Start',...
    'BackgroundColor',But_color,...
    'Callback',@Start_NN_callback);

hButton2=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[285 70 150 25],...
    'String','Neural-Genetic Start',...
    'BackgroundColor',But_color,...
    'Callback',@Start_NG_callback);

handles=[hButton2,hButton1,hButton,hTSSE1,hFR1,hTSSE,hFR,hepoch,hMom,hLR,...
    hNuIm,hGToF,hGen,hCoRt,hMuRt,hPopsz,hR,hRTime];
set(handles,...
    'Units','Normalized');
%% ******************** Callbacks  ****************************************

%first button callback for run genetic algorithm
    function Start_GA_callback(hObject,eventdata)
        reset();
        tic();
        Gen=str2double(get(hGen,'String'));
        Pc=str2double(get(hCoRt,'String'));
        Pm=str2double(get(hMuRt,'String'));
        Popsize=str2double(get(hPopsz,'String'));
        R=str2double(get(hR,'String'));
        [Total_Fit,PopB]=GA(Popsize,Pc,Pm,Gen,R);
        time=toc();
        set(hGToF,'String',num2str(Total_Fit));
        set(hRTime,'String',num2str(time));
    end

%second button callback for run neural network
    function Start_NN_callback(hObject,eventdata)
        reset();
        tic();
        eta=str2double(get(hLR,'String'));
        mom=str2double(get(hMom,'String'));
        epoch=str2double(get(hepoch,'String'));
        R=str2double(get(hR,'String'));
        [TSSE,FR]=neuralTrain(eta,mom,R,epoch);
        time=toc();
        set(hTSSE,'String',num2str(TSSE));
        set(hFR,'String',num2str(FR));
        set(hRTime,'String',num2str(time));
    end

% third button callback for run main neural-genetic algorithm
    function Start_NG_callback(hObject,eventdata)
        reset();
        tic();
        eta=str2double(get(hLR,'String'));
        mom=str2double(get(hMom,'String'));
        epoch=str2double(get(hepoch,'String'));
        R=str2double(get(hR,'String'));
        Gen=str2double(get(hGen,'String'));
        Pc=str2double(get(hCoRt,'String'));
        Pm=str2double(get(hMuRt,'String'));
        Popsize=str2double(get(hPopsz,'String'));
        [Total_Fit,PopB]=GA(Popsize,Pc,Pm,Gen,R);
% for test program and compare reported results about neural network
% learning after tuning weights by genetic algorithm please activate the
% next code line and deactive befor code line (line 423)---->deactivate
%                                             (line 429)---->activate
%                                             (line 430)---->changed
        %p=load('PopB1.mat'); 
        [TSSE,FR]=neural_genet(PopB,eta,mom,epoch); % if active before codeline then replace 'PopB' by p.PopB 
        time=toc();
        set(hTSSE1,'String',num2str(TSSE));
        set(hFR1,'String',num2str(FR));
        set(hRTime,'String',num2str(time));
    end

%define function for reset controls and text boxes
    function reset()
        set(hTSSE1,'String','');
        set(hFR1,'String','');
        set(hRTime,'String','');
        set(hTSSE,'String','');
        set(hFR,'String','');
        set(hGToF,'String','');
    end

%**************************************************************************
%********************************End Function GUI**************************
end
%**************************************************************************
%**************************************************************************